[workspace]
members = [
    "reverse-string",                 # 1  easy
    "gigasecond",                     # 2  easy
    "clock",                          # 3  medium
    "anagram",                        # 4  medium
    "space-age",                      # 5  medium
    "sublist",                        # 6  medium
    "minesweeper",                    # 7  medium
    "luhn",                           # 8  easy
    "parallel-letter-frequency",      # 9  medium
    "macros",                         # 10 hard
    "poker",                          # 11 hard
    "forth",                          # 12 hard
    "armstrong-numbers",              # 13 easy
    "beer-song",                      # 14 easy
    "difference-of-squares",          # 15 easy
    "grains",                         # 16 easy
    "leap",                           # 17 easy
]
resolver = "2"

